OPENGATE_HOST = 'cloud.opengate.es'
NORTH_PORT = 25281
SOUTH_PORT = 9955
OG_NORTH_API_BASE_URI = 'http://{0}:{1}/v70'.format(OPENGATE_HOST, NORTH_PORT)
OG_SOUTH_API_BASE_URI = 'http://{0}:{1}/v70'.format(OPENGATE_HOST, SOUTH_PORT)
ORGANIZATION = 'your_organization'
CHANNEL = 'your_channel'
API_KEY = 'your_api_key'
DEFAULT_DEVICE_ID = None
DEFAULT_WIFI_ID = None
